/* This file is part of higgs-boson.
 *
 * Copyright (c) BitBoson
 *
 * higgs-boson is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * higgs-boson is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with higgs-boson.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Written by:
 *     - Tyler Parcell <OriginLegend>
 */

#include <BitBoson/HiggsBoson/HiggsBoson.h>
#include <BitBoson/HiggsBoson/Utils/ExecShell.h>
#include <BitBoson/HiggsBoson/Utils/FileWriter.h>
#include <BitBoson/HiggsBoson/Configuration/Settings/PeruSettings.h>

using namespace BitBoson;

/**
 * Constructor used to setup the Peru settings object instance
 *
 * @param peruFile String representing the path to the Peru file
 *                 the instance is going to manage/overwrite
 * @param peruSyncDir String representing the path to perform Peru
 *                    sync operations in/to
 */
PeruSettings::PeruSettings(const std::string& peruFile,
        const std::string& peruSyncDir)
{

    // Setup the local member variables
    _peruFile = peruFile;
    _peruSyncDir = peruSyncDir;
}

/**
 * Function used to add a dependency to the Peru settings object
 *
 * @param name String representing the name of the dependency
 * @param type DependencyType representing the type of the dependency
 * @return Boolean indicating whether the dependency was added or not
 */
bool PeruSettings::addDependency(const std::string& name,
        DependencyType type)
{

    // Create a return flag
    bool retFlag = false;

    // Only continue if the provided dependency name doesn't exist
    if (_dependencies.find(name) == _dependencies.end())
    {

        // Add-in the given dependency name
        if (type == DependencyType::TYPE_GIT)
            _dependencies[name]["type"] = "git";
        if (type == DependencyType::TYPE_CURL)
            _dependencies[name]["type"] = "curl";

        // Setup the return value accordingly
        retFlag = true;
    }

    // Return the return flag
    return retFlag;
}

/**
 * Function used to add a property to a dependency in the Peru
 * settings object
 *
 * @param name String representing the name of the dependency
 * @param property String representing the new property to add
 * @param value String representing the value of the new property
 * @return Boolean indicating whether the property was added or not
 */
bool PeruSettings::addDependencyProperty(const std::string& name,
        const std::string& property, const std::string& value)
{

    // Create a return flag
    bool retFlag = false;

    // Only continue if the provided dependency name exists
    if (_dependencies.find(name) != _dependencies.end())
    {

        // Only continue if the provided property name doesn't exist
        if (_dependencies[name].find(property) == _dependencies[name].end())
        {

            // Only continue if the value is non-empty
            if (!value.empty())
            {

                // Add-in the given provided value for the dependency
                _dependencies[name][property] = value;

                // Setup the return value accordingly
                retFlag = true;
            }
        }
    }

    // Return the return flag
    return retFlag;
}

/**
 * Function used to perform a Peru-sync operation on the configured
 * location/directory based on the supplied peru sync directory
 *
 * @return Boolean indcating whether the Peru sync was performed
 */
bool PeruSettings::peruSync()
{

    // Write the Peru file to disk
    auto wroteFile = writePeruFile();

    // Write-out the Peru-sync shell command file
    bool wroteSync = false;
    auto peruSyncFile = FileWriter(_peruFile + ".sync.sh");
    if (peruSyncFile.isOpen())
    {

        // Write-in the standard Higgs-Boson header for the Peru file
        peruSyncFile.writeLine("# THIS IS AN AUTOGENERATED FILE USING HIGGS");
        peruSyncFile.writeLine("# DO NOT EDIT (UNLESS YOU KNOW WHAT'S UP)");
        peruSyncFile.writeLine("");

        // Write-in the actual Peru-sync command
        peruSyncFile.writeLine("# Run the Peru-sync Operation");
        peruSyncFile.write("peru --file=" + _peruFile);
        peruSyncFile.writeLine(" --sync-dir=" + _peruSyncDir + " sync --force");

        // Close the Peru-sync file
        peruSyncFile.close();

        // Indicate that the sync file was written properly
        wroteSync = true;
    }

    // Run the Peru-sync command and return the results
    return (wroteFile && wroteSync && HiggsBoson::RunTypeSingleton::executeInContainer(
            "Synchronizing External Dependencies", "bash " + _peruFile + ".sync.sh"));
}

/**
 * Internal function used to write the internal state to the configured
 * Peru file on disk
 *
 * @return Boolean indcating whether the Peru file was written
 */
bool PeruSettings::writePeruFile()
{

    // Create a return flag
    bool retFlag = false;

    // Open the Peru file
    auto peruFile = FileWriter(_peruFile);
    if (peruFile.isOpen())
    {

        // Write-in the standard Higgs-Boson header for the Peru file
        peruFile.writeLine("# THIS IS AN AUTOGENERATED FILE USING HIGGS");
        peruFile.writeLine("# DO NOT EDIT (UNLESS YOU KNOW WHAT'S UP)");
        peruFile.writeLine("");

        // Write-in the import section of the Peru file
        peruFile.writeLine("# peru import information");
        peruFile.writeLine("imports:");
        for (const auto& dep : _dependencies)
            peruFile.writeLine(" " + dep.first + ": " + dep.first);

        // Write-in the catch2 integration for use with Peru
        peruFile.writeLine(" catch2higgsboson: catch2higgsboson");
        peruFile.writeLine("");
        peruFile.writeLine("");

        // Write-in the plibsys integration for use with Peru
        peruFile.writeLine(" plibsyshiggsboson: plibsyshiggsboson");
        peruFile.writeLine("");

        // Write-in the individual modules sections of the Peru file
        peruFile.writeLine("#");
        peruFile.writeLine("# peru module information");
        peruFile.writeLine("#");
        peruFile.writeLine("");
        for (auto& dep : _dependencies)
        {

            // Actually write-in the individual module section
            peruFile.writeLine("# Setup the import for " + dep.first);
            peruFile.writeLine(dep.second["type"] + " module " + dep.first + ":");
            for (const auto& property : dep.second)
                if (property.first != "type")
                    peruFile.writeLine(" " + property.first + ": " + property.second);
            peruFile.writeLine("");
        }

        // Write-in the catch2 library download
        peruFile.writeLine("# Setup the import for catch2 integration");
        peruFile.writeLine("git module catch2higgsboson:");
        peruFile.writeLine(" rev: v2.12.4");
        peruFile.writeLine(" url: https://github.com/bitboson-deps/Catch2.git");

        // Write-in the plibsys library download
        peruFile.writeLine("# Setup the import for catch2 integration");
        peruFile.writeLine("git module plibsyshiggsboson:");
        peruFile.writeLine(" rev: 0.0.4");
        peruFile.writeLine(" url: https://github.com/saprykin/plibsys.git");

        // Close the Peru file
        peruFile.close();

        // If we get here, mark the operation as successful
        retFlag = true;
    }

    // Return the return flag
    return retFlag;
}
